travis:
  secure:
    BINSTAR_TOKEN: Yo2ExDXl6I2D9ouHRs22q79jImR/uPUyJ/TzDtN279V5YOdIG0ySh/roGbITNpZTqP4QcSR1k82ImDHzDjCYoAsbMKn2bEvcFrus/UIcoFhKf0snRt2ameimbV4cLPc6bFK4wd2dx+6KWva7G0GXdVK2I2aFCyF4bRoBOQmYYS2uA50F7zt6nEj+5WukcqC39I0lpE/VZU+eNk3OkmBcISwdTJGKCt6FG2OCof0tfVoJwqESe4GbTO2v1zujiDKAF4G0x/2+qKu6AxsUAkjSn+xKkcyYMjSTYsKbkyP+6mCtIGyMvn7QYk6DQ19nJUVNNanGVFPbjKqWnZC6oTxhhv/L7kKOTvagZrcKYvRYlPj7hJ/h89ddDjMLR5VWo/4/gsZbXRT5XA7WKa95amQXa5Ukje6yJoEevaYaTSBuLqPpvftTpxii0/UegVatxT8/kJ85etnGNTYBVOLnBj6M09EG242w1V/4rgBQgqimuPPGZ+DCD/+kC8aFgt/EoersYantwmIkAr45zMZlC3wo3ACIcPtDgSAg6HxX94PPousrUeA1F60+F3CaehP2mPUHOFHErP7RECYGU4/hG6vBzEAIBdhQditi4hpBNpJbEkpHbcz4BPejoTD3zJR+3bpTc+FlAiY3hSxEGHUS2WF7FKSgkKMGCZm1E+nFuF3/Hsg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
