{%set name = "urllib3" %}
{%set version = "1.23" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "a68ac5e15e76e7e5dd2b8f94007233e01effe3e50e8daddf69acfd81cb686baf" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    # secure
    - pyopenssl >=0.14
    - cryptography >=1.3.4
    - idna >=2.0.0
    - certifi
    - ipaddress  # [py<=33]
    - pysocks >=1.5.6,<2.0,!=1.5.7

test:
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.packages
    - urllib3.packages.backports
    - urllib3.packages.ssl_match_hostname
    - urllib3.util

about:
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'HTTP library with thread-safe connection pooling, file post, and more.'
  description: |
    urllib3 is a powerful, sanity-friendly HTTP client for Python. Much of the
    Python ecosystem already uses urllib3. urllib3 brings many critical features
    that are missing from the Python standard libraries, such as thread safety,
    connection pooling, client side ssl/tls verification, support for gzip and
    deflate encodings, HTTP and SOCKS proxy support, helpers for retrying requests
    and dealing with HTTP redirects.
  doc_url: https://urllib3.readthedocs.io/
  dev_url: https://github.com/shazow/urllib3
  doc_source_url: https://github.com/shazow/urllib3/tree/master/docs

extra:
  recipe-maintainers:
    - pmlandwehr
    - sigmavirus24
    - ocefpaf
