travis:
  secure:
    BINSTAR_TOKEN: 3/5gvefTA6RtFFaXRSiFOO6tdjNE1FvrUR9VLAYzuQDerX+jKVM8xTrBv5GcAJDMZWWxX2A5ybKFXbAk04J4XOZ9n9shkB6aYfgBtWhiGRezO+D/OoeysmFD9CzbvCAmdL7hGY3JWE96QE3xrWAoK3qzA6cPMr+ZJDMzicuXmSuZbv68ZuxHhPB18myLeQcKT4Wn+Hk+r1CqpDnR+1iq+WX2lz/5XHsrtqjpUEjrU/2bPrfaOmzMsIsrD2aEJnZgAmmwp/wgJNIqbv5ahq/tIOuhWd+7uTFnetSzjc7oSxkZOmidaQ/RLGrgQ8YNBSXDVvoVOto2V/5RhA0jbdeK0x33+YMLChXj9s2Eg6u4PiQCUu9BFZ48VSiJhuH5kuh5CiPifDOTNU++D6VRtNRSoVd3lfWdsE7hfVAotTGAKjkfxNauVnmSp7vhOM4hY8qAswgNHIaywPYCuVT3yYR5uRi+FoJbYvIV67do0Q5MauLD63s6x1PZkSWavC/hVBnjF9jgS4nXymILiOuJWRTo8NekTs2q94lriK9BkjBB6AIXlknxvJ2V07A3dfBN7nZi7Kpug7u4XaWfgEq3gc4yOmIvRLrjH6YULbzjbNtRg15X9ba8NnIvijFcGnogmfOuriM+TGExe9Ml8DqAgutG9hFxd5opjojBjNhOHWWoKC8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
