travis:
  secure:
    BINSTAR_TOKEN: u9Zjb0ZwUqDNR9Th4JQP3oRXC5O4d9MLyk5IxOwKCrTf9+gW9ARndy4ontDBz+mR/lFJCbzQm1cvBm3qkP54YXi4KUXZMKlgPcV8wraqOAbQeHWV+S5NtffQxgulBd8jnX/+aAX9T/X/pLTB0rNt8CcEB2nA253D6vyU4hGNOQ8spjJftwa50beTUPPdZegRwliUIMoF9PHf7zktNWbk+Hu1Knl4TAKJ7nzDdqp8/SqcFqGOzcb628jMNnRZ5PoP6OkMlmDnMjqTDbRwQcQmFNVBzV0xCEsDymaxtOZLiq8VnaEPIjwSzRAH0S+EiBljW8rNxSNGWiIZHe5Vy+Exm9tMKpdmGl14fkF6LkO6Bg9bPQBr7XSi2OVTQaxxGYCrIEzg/u/WxVqWgLj5FIDcIOF1M2Xd8kg6MJ5lroIrRxlpA8YfCNo1JKm1pHmV+dL2ggkK/P9Me0tYdUIqJ4n92NFa4wrAuI4Em9SDvCMyKI91bD0ptq2fyWjNQE++MoqdjGZ1UmLDapgAdmWKWuWW3W7n2JACaNPiRs+6O1ddlBMP5BZrc5N2jwU/1XzuRCWhO6JxU5xm4W/Ufsif1C0V91Y46qVekn6L9pKJVmnU97GzPKWqceC8VNq+OvXr0sWQJ+EX2QTTrdaojbcIvqfCSXtqnTuBLTuLjb3Q9bgOBz4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
