travis:
  secure:
    BINSTAR_TOKEN: T5QXlH0PhvgVEL21QGQWp7JDIgL6Kv/A7XaewIbTlY2HOJiCRoXJSrxpMl5fzB6ea8hJ0SHnXeSGGIxM/z9p1rLKIjbKrKsdCUZTwGZqhp7VEoUydofvunkZyc3TBZHGiHyO58VDsnT7z47bSOAOwiHAX3syPBxsVvDiQYJdN0Wb+rFyqP/1XefqEO+pV5BOVynCoUltS+LzOFhhOpjiZh3lmf6s0aWjaL4+RwFWI9Ptsmj/qRN/SLa5ErsPPgfv6YZKFj6HEhOv0eHpJ5HHdf4XtoRcfPwuc9Q4EHfZC/sU7t/Uny+sHTLm2M5PZVtOIBCLsyUohrfPgYgmkIk0DAmhu2L189B87FjcrX49XQcSsUI36jtXODL2fkvS7L9Lgd9Pz+7boRMnTrO6UbKDYeAb5B/G9dD25BxXL2cyQ2PqEqbaO/twoqxhzYW7Kmt21p7HHJUz5HOQOlSj0jUi6m+J/6sq+oiH6846+tfiX2IT+AVezXVFCj+ay090ZZXo5VN0TILa5qmvEd0IwHJY1SCaKANGJpLFrq4/VDjaYGNF/zIi714yFaVwHHG3pdsF/mu0ugqeoA4NOGA32/XKwXvgDCzgVHyHyo5M9oOlpeqAnQAlONggQ1pDUwZ1YGDFaKypagetWRZD6loeJihiAzshyjZZ/SX/j1Hs79TmRmM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
