package:
  name: lizzy
  version: {{ ctng_gcc }}

source:
  path: .

build:
  # defined in conda_build_config.yaml so that we can keep it associated with a particular GCC version number
  number: {{ ctng_gcc_activation_build_num }}

requirements:
  build:
    # this dep is for us to be able to use gcc -dumpmachine to get the CHOST value
    - gcc_impl_{{ ctng_target_platform }}

outputs:
  - name: gcc_{{ ctng_target_platform }}
    script: install-gcc.sh
    requirements:
      run:
        - gcc_impl_{{ ctng_target_platform }} {{ ctng_gcc }}.*
        # for activation of binutils env vars
        - {{ pin_subpackage("binutils_" ~ ctng_target_platform, exact=True) }}
    run_exports:
      strong:
        - libgcc-ng >={{ ctng_gcc }}
    test:
      files:
        - tests
      commands:
        - ${CC} ${CFLAGS} -Wall tests/aligned_alloc.c -o c_aligned
        - ./c_aligned
    about:
      summary: GNU C Compiler (activation scripts)
      home: https://gcc.gnu.org/
      license: GPL

  - name: gxx_{{ ctng_target_platform }}
    script: install-g++.sh
    requirements:
      run:
        - gxx_impl_{{ ctng_target_platform }} {{ ctng_gcc }}.*
        # for activation of gcc env vars
        - {{ pin_subpackage("gcc_" ~ ctng_target_platform, exact=True) }}
        # for activation of binutils env vars
        - {{ pin_subpackage("binutils_" ~ ctng_target_platform, exact=True) }}
    test:
      files:
        - tests
      commands:
        - ${CXX} ${CXXFLAGS} -Wall tests/aligned_alloc.cpp -o cpp_aligned
        - ./cpp_aligned
    run_exports:
      strong:
        - libstdcxx-ng >={{ ctng_gcc }}
        # Because transitive run_exports do not work:
        - libgcc-ng >={{ ctng_gcc }}
    about:
      summary: GNU C++ Compiler (activation scripts)
      home: https://gcc.gnu.org/
      license: GPL

  - name: gfortran_{{ ctng_target_platform }}
    script: install-gfortran.sh
    requirements:
      host:
        # So that pin_compatible has something to work with:
        - libgfortran-ng {{ ctng_gcc }}.*
      run:
        - gfortran_impl_{{ ctng_target_platform }} {{ ctng_gcc }}.*
        # for activation of gcc env vars:
        - {{ pin_subpackage("gcc_" ~ ctng_target_platform, exact=True) }}
        # for activation of binutils env vars:
        - {{ pin_subpackage("binutils_" ~ ctng_target_platform, exact=True) }}
    run_exports:
      strong:
        # The SONAME changes at major releases.
        - {{ pin_compatible("libgfortran-ng", min_pin="x") }}
        # Because transitive run_exports do not work:
        - libgcc-ng >={{ ctng_gcc }}
    test:
      requires:
        - cmake >=3.11
      commands:
        - pushd tests/fortomp
        - sh test_fort.sh
      files:
        - tests/fortomp/*
    about:
      summary: GNU Fortran Compiler (activation scripts)
      home: https://gcc.gnu.org/
      license: GPL

  - name: binutils_{{ ctng_target_platform }}
    version: "{{ ctng_binutils }}"
    script: install-binutils.sh
    requirements:
      run:
        - binutils_impl_{{ ctng_target_platform }} {{ ctng_binutils }}.*
    about:
      summary: The GNU Binutils are a collection of binary tools (activation scripts)
      home: https://www.gnu.org/software/binutils/
      license: GPL
