appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: vo59CZGamBYZpRIDxMx1lPjaQ4WKHEEkdNdw97CqsZMFDBNPNtz12tqOJF8R6GBHnVMNX4E2/9VyWsUccL/OmYkhYqpqXbZXwhwk3tyo9215fZ1EcrAbzPfZBn4cZpn1hR/Kh1pOvg+dWD3M2LT+Hlbc0WlNzKSJVwcgkmsd7H5Kyb2TIe3bzbaJHCsNJoYoAY1NPTZ8DtsQi8/wG56328ZMuiixVJxPKHo6DGksMGNtw324SOQQiaM6YJK+DP257ryHhPgIWk3bCLiSfDp3UhukuOeW1ft/8tzzdQhKJe0hNnIIxFiaB3QjbTUOZGd+ZgX8BHmpDBR6GJZnJvAmgOIXTN4+O9OqDIeUd7ig5vWgnZD3iqDZSTU2Se3X4oWK66JsK+tcmR2z5KAEnaT5uvkzu/qGuly4Ed2uXmyKWmxzAqizX7laD6SPBhBRDeNG8kMqODV4VuFwpAucFpOhsIzvRMHY3AhKO4DoHtztMuEszrjpokss8xWY5nXYbm/T7L0EEsqo2q4imZNwx4dUO+aDuRHLYgL9z0fm30ixDFgfYE4f1hOlPLvxmXjOpg2q6E3qtFTT9ihaTfta9DJqvnKboYLy8T7oboV7c6a3yFAO6p7G4CFemJseEhDRR16sekP/L0nouH6S1MF3vqkobi5zNhzJOJGitt42MzEigLk=}
