appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZMxuH0LDg9UBslnnMo6MJ2yZRJJtqkH3cwByOWsJPl4LsrqHnk+WvjgQjcax2QUvOea4K/wXNDUPA5bkwZZ8U+RshZq1yTxGp34Rk/DoCpzW6wueC7+pxnIwNgMd350irq/aRgA3rBnKJu6WUmUQYC2DZjvESnGkYo61zBv08sZaxne+9f3cuTOOfzrHsbKSq/ey5/K9GI/oUb4kyNgJGb8OM8rhaQDvfxjSuP/yeqbsCvsW3LL64DK8+iSYb8csK4u2S1w6Wfb6PeISwVS0bpcpvRZoyOicq7BqEY1GS/BT8GriIrfYItGzNDR2XQSrLprDBczNz8MZZL4/2Bv8k4sEhf3VpKNKmO85opJZMO0IhNXgDZQzqmPnSEVydIa8bDt0HJJg/M1SAKmAE0pFmcjUxtO1XYuR7DCHf5aTFXFtmbVRBpuLIp1/oAS4r2bNY8hFhwV0GH+/NUtAnXFmgkG/ts+xawhOFEZpb2MF5dtkF+hrnYuMVSfr874G11gpvU/vJeYGMJML9BbriXeQ8wZJddnSL/09LaPj3UfzHJKb12LpUyivGus+PNgCX8+oZu+DDVXqzphBOPqwMAsKH1omdSRYYrG+jTuelSLKKL91vPyr4FU2Kot3pIwjdR63IF/EPUjcpSMENtaakWuevXHSLWdzsI1sVtD/OEXdAz4=}
