{% set pypi = "libarchive-c" %}
{% set name = "python-libarchive-c" %}
{% set version = "2.8" %}
{% set sha256 = "06d44d5b9520bdac93048c72b7ed66d11a6626da16d2086f9aad079674d8e061" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypi[0] }}/{{ pypi }}/{{ pypi }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Add-zstd-support.patch

build:
  number: 7

requirements:
  host:
    - python
    - setuptools
  run:
    - libarchive
    - python

test:
  imports:
    - libarchive

about:
  home: https://github.com/Changaco/python-libarchive-c
  license: CC0-1.0
  summary: Python interface to libarchive

extra:
  recipe-maintainers:
    - bollwyvl
    - mingwandroid
