travis:
  secure:
    BINSTAR_TOKEN: BYIWcmQec98yd9ZhSfvSoqpkMhbauUib28nAxZUymNx/UA4fxdsvys8ky3DZVl1AT+iZMRgLDRNoOmGkVu1ZIwYUnUb0yB2EsGc5FZFxOgwzKGaIBPsCM9VSIaLrYj93lWY20w0RlUTDw2dDUlmxT2J0t6CpCK0NDAsrvoS8VWDbuACvZtFQr+XZlw2ux9qmFxB335YJAsTYXNE4PUbNnTpaT7GLeFSGtHZRyAjgDdzXgD6K+QBaKLWsgmhnJ2idT63c65xkaVKlS3OqZ9zciCBFLTW7u7HmHVGJd7w3MbuMDoQ5v9K15od+t7TGdiOuZdDK8LvK+Rrfnc6s2LJ5V7FoXFMBPa2m0X6Q9zK/MA71RdkQrbYDOXur15M8QPDykwZc0zsEwCimjVDT2+fKBEY0L88eXgcWCb27uiA5LL8Zm19aK1LDvskyVoeChp4aJC4vXJfBrJC8PM6fN6Jb8vX+0VI99VMrHTw+xU/0MaEbWrUbwgpAxy9dv/cQcX+2Zk3nyvx9YW/mn2f0QvWXpv6qwtb5xtbMjS3JM4ugysRv07tLUgGWme7tEfXyYI4As3Xv5G/bHi8lkwYr2W8LMVb5vkFW1cUVA8bEds9fXsmwksKUu2xzVM66p/UwRVoQtA29Kqr+OAi6MXjzi1g28lpKhUcDdeUV3CbqzdyyQ4c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
