travis:
  secure:
    BINSTAR_TOKEN: 13kuPsZ4uPVWbfwzy7hs5y5QckKWKYECa6nTSs2BoBYoSL9QS2Fa9w+pGAOOcCjKQT01t45tq0FRRyB6yaMYvYlWDLnjen3QjkKoTV6Ty5+DB8OF5TcHOZYTKTUA3ps1V4KPViOwuhxk5ChiCgJsugzGOU5bKuIcMWvBU8FaXIxARdRbaF4tnTwF06X8KOCtZwuQRGUOdjhAS0hnm4oXA6hqdsZHBnJY5eS6DsdYQAWD7eM2OCJyIj4ROC0f+coHny+JOb33/0wecT3M+0z/4pWN8BRWcv49EQuSLdSSMCJVyX/cLpwU71o5o+caSiHRAhIi0ieCqI3+Tq3ye4/bG8zgtrObJ/mklpe/ihwyzKp9Vc3Ex7MiOjSkWPQUdtTQNAWqzFJZtQaZBFR5YkhWVDgq2z+mI1tGgG+HRznJxxbY9pPZtdhOj+Rf53uQsLQE3pACNpnnetcMz3ZI8nXse61IQKNsQGIsu0v93hDNmasRxs6ONA5oIjXYzobUjdk92u5dzQPU7ilF7YC1wcnFQUlsC+YYCcI588bTkN6VANgUiMF2bVUevuRynQH98NDgp+LxhOEjDdfa7ujg5WTQ9Unpfi4/6SzufIvaxCdvmt2MV79qw57C4DzzmiiOt2Z7lEMpXawLK7W23psAOXf2DGa0v9JZNKpEjqcrmhQ9RP4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
