{% set name = "pip" %}
{% set version = "10.0.1" %}
{% set sha256 = "f2bd08e0cd1b06e10218feaf6fef299f473ba706582eb3bd9d52203fdbd7ee68" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0003-Ensure-that-clobber-breaks-hard-links.patch

build:
  number: 0
  disable_pip: True
  entry_points:
    - pip = pip._internal:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - wheel

test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip

about:
  home: https://pip.pypa.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
  doc_url: https://pip.pypa.io/en/stable/
  dev_url: https://github.com/pypa/pip

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
    - ocefpaf
    - mingwandroid
