travis:
  secure:
    BINSTAR_TOKEN: DjT1h7iwrnkvzU0TlwekHfj4kf0MJCfhYtcDQwG77gmWdIZuNOg7aVUoY4NW4faLGu9mo9sx2GyZnSj0H7qa0TFPMSq/nNU3POHXB9GKe2ArwNbVzQ2BWvlTJ4v39QEELnxVUb9iMlPQlZAV3nnBOQOMU/8roBalWxasUzQlcdn5X0XxXMTHsNdovDmBh8eMumb5bcHAwXjUz+mP5v4hL5WcmCq+niGhxf7N22iSFoyDh+mezxFOU29UWEON9jvexGBsn0rzlFDvFwoOsDty+sD2u1njZjD5igB9nZyipTH3UP2Yl3IapcuN6H4zQBOIBbAJ2WphGm6hdFkVsMdke7lwUyRtkO50PTeK5YONrk3EJ1iE57D/DvDIlay3D1g7wnPepWAduI1W/6pwbBvCr6ohQE96WlhQx/+bN5bIcqo+HtAUd0+jr2EkagrWXVlWaQw1/PDE9gIWaxiVaeJwS+e50odnCKrQ6BYpz58yKEbvN4fFXKBaa0e9zRLTJpzj3eWuobRHRG4n4ls0+5aS1CVa02p90kuZ3LccseY+fzifSHIJlbFMEbBipOqGADokFZTcq/0vdoWSeSEiUSrQgOAEuhV5lObgQs39v5TWphGg05JQHVwF93u6EUCP3v+yFz2WnSNwgPusYTWAyri5+Ha7TrrEj1iCJctq7MbrAUo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
