travis:
  secure:
    BINSTAR_TOKEN: CPJVvOQF74N0nid7wNyeNJeaXPpnKLrSgPJd98tceKOit4W5Wv5Q+C/PFKCwKHNOnA6i45y2mkGw2PVUpjzWtGgAcnfcTxpbirEBRU07UTLLeyex4DaRxdNEvqSlB5y+CIogsf7CKsv8PDUV/Q7jNwUtydkAtTFkWfTFTcVu0dXqEeNloR6YN6l6VbX27+DBGDGdxCKtQguXTPbur1Y8FRNx6aVUUm4zy/ED4k+UYfOMN3J8KTQFMzhQMQ2lYyXDwUX77h6sJhEVk034hA23sP2ACwcg8ERF2qbHr2Nuz/8gsSaA67E28WI1y01IyFDq+Oh9dgCU0fedDyyDv2+NQ7u9ItyD0R9WKu/BDFpZJoiStVnpqet6pAuXYAvOAmg3Y5dky3U+Bub9bpz7hmnZ/waY9de8jvcyGdSXYoeA1cV9lMrT/hGuh1JPEhvj3V/wjd1r35GWVVGesTMAJ5meDIz1eboyIRmy2Mnd+HttiujpObUH9NFeb67TUS2IYMNhhdXAMJTkYYRbB1nYs1PqBu6InVeEpbEA8uIYYZ0uP3bcOA41na3mul16AVI0TESE57WZE5cdPR64TDnzsX4Ej9vPxFKshnRVZJ95J9aTTgszCxDt2zLMrkqMUqSIbgxKaJTKaD3svEsRkulH5fnY0KAxMffzuQyjR4UJrRP6rLA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
