travis:
  secure:
    BINSTAR_TOKEN: gdTVV2AUFeBpjwChLGKFqLumKQm06q6HczQISuNPUKZLIVWteIX3fdrLP8GXYTAY1LF5nZnuUL6lfBXVVK2t3poUW/lwyQ8JG8hDxPRNFNkESCDzlDXKOQMcEgv6A6b0zytxNQUYp6MEoH7h1F2oovaieGtg0WE5xEqtDHPnVCqGS4xZQ1VZMQQXMoZsGGcr+9t2VoHUuy0Q1fAsFO6hyCX3nYlo7niuu2OHv/CybLSkCg5VAY7dTkR5RHcRDM/CHnKV0kF8sPB9vnMC88U8HDt2Fso4OPdh/joryuhEb87elW1p30cp3VYEzCCxZ6l/VzNCP1EEso6SSQBLcq8b7aPwxTN6a8P3TOq45jqge+cfbCni7PZhVrKlN+nghOqMfx8+3NLPQlKSooy0CmgWIGAGqoQEmZzC92z/9dc1e+Gf4t/Iv0SwsP+eBd4PPtKpPlVXOwlKSQdrOWpEN11nWEea8c7I3OYpMZKSVtsI/NhMeLDrP3XwU8KY0moCQcy3zI4iKmQicuYhqkwOW9GKr/tZ1qlIzxvQdfTZ+s26wthQ7GyEY4pzjxSNqsE3QfH+d20vRfDb6TiyBvF9Mo74ZkJ/CNt0C0pfP0WD8JHF3KEGsmWmDaH7VhDH3HsnZZBiHRqRrxAstO7ISEOfnvCll1yYvlMj8mNzgre6xKk5UIw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
