# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Vf5TZaNdHlfucI4I37mJvhUpbIm0UUIGJIgLRxG2DQ5JjNv09GBhVeACnYhXyUBcWYb+zHJHmwseP5cP5gd/4LH1rN8Ktw6f4Q7Gff6oag5xNm90dHGyxnO2xoXaH0ETDbNyQ8L8U0im2+BG+vd9LW0/NTNPzwI7C6uDKBIXm4xN0r77UdMWJBQfM/VBPX8PgE2Rv9S+xBOhyk/Es21SgVxiYFYQus4yAoT5Aw1b1bYfLU2Gs4ugO2wP/jflck8JIF5fn3eYJyCikGpbqsm5Lj+UVw8h31hEUvyVcdQJpwnMb0p7+LaQye8VgUDmul0r5il75klKgXZutDt1bKpD3vKgHXnHgxqllDo1Nsp7hJry8JctiYJ4+qq0Iv79wc3J0HIHDU00DyA1nCk8Mxy4GDNTNFXJO1Ot4gj0OhlqoEMLHjj0fd/Wypof8PLGHKiVB8nzH2KOUxSbO/QsbbtckPFO3mgwyeC/Hx+ZWdpvUbCx6uAhv0WrPQ4+Np9tFU62emMyusepAMOpReCe907StEmzT/iIhQxqO6AIyYpnvlixFIu13OqQ/xx1OgPRpjchtTmbaRU2SXoxAq4nfgun9ujlMqUA+zf/BVLG2+nUP81m14enxv32lsECcxdY0TZ/Sl+EuxG0Ud9Dg7T9ZS4vDdwglsPChniOtlRmcbom4t0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
