travis:
  secure:
    BINSTAR_TOKEN: Vf5TZaNdHlfucI4I37mJvhUpbIm0UUIGJIgLRxG2DQ5JjNv09GBhVeACnYhXyUBcWYb+zHJHmwseP5cP5gd/4LH1rN8Ktw6f4Q7Gff6oag5xNm90dHGyxnO2xoXaH0ETDbNyQ8L8U0im2+BG+vd9LW0/NTNPzwI7C6uDKBIXm4xN0r77UdMWJBQfM/VBPX8PgE2Rv9S+xBOhyk/Es21SgVxiYFYQus4yAoT5Aw1b1bYfLU2Gs4ugO2wP/jflck8JIF5fn3eYJyCikGpbqsm5Lj+UVw8h31hEUvyVcdQJpwnMb0p7+LaQye8VgUDmul0r5il75klKgXZutDt1bKpD3vKgHXnHgxqllDo1Nsp7hJry8JctiYJ4+qq0Iv79wc3J0HIHDU00DyA1nCk8Mxy4GDNTNFXJO1Ot4gj0OhlqoEMLHjj0fd/Wypof8PLGHKiVB8nzH2KOUxSbO/QsbbtckPFO3mgwyeC/Hx+ZWdpvUbCx6uAhv0WrPQ4+Np9tFU62emMyusepAMOpReCe907StEmzT/iIhQxqO6AIyYpnvlixFIu13OqQ/xx1OgPRpjchtTmbaRU2SXoxAq4nfgun9ujlMqUA+zf/BVLG2+nUP81m14enxv32lsECcxdY0TZ/Sl+EuxG0Ud9Dg7T9ZS4vDdwglsPChniOtlRmcbom4t0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
