{% set name = 'cookies' %}
{% set version = '2.2.1' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: cookies-2.2.1.tar.gz
  url: https://files.pythonhosted.org/packages/f3/95/b66a0ca09c5ec9509d8729e0510e4b078d2451c5e33f47bd6fc33c01517c/{{ name }}-{{ version }}.tar.gz
  sha256: d6b698788cae4cfa4e62ef8643a9ca332b79bd96cb314294b864ae8d7eb3ee8e

build:
  number: 1

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - cookies

about:
  home: https://github.com/sashahart/cookies
  license: MIT
  summary: Friendlier RFC 6265-compliant cookie parser/renderer
  description: |
    cookies.py is a Python module for working with HTTP cookies.It can be used
    as a replacement of Python's Cookie.py (aka http.cookies).
  doc_url: http://cookies.readthedocs.io/en/latest/
  doc_source_url: https://github.com/sashahart/cookies/blob/master/README
