travis:
  secure:
    BINSTAR_TOKEN: A2FqLxFlwsRui7g5RgvImSTB2jnGNK0AbiAsgQf6VxOJE/ODZmbPc/CIkEohPFC62N0Z+Red+8EOxQusX2xLE/JmuQ/Gd6mTb5RoH6wiKlKEQ127yRrPy+m3TnL95ddK9B8jM1DgtdG6u99++mjScE3MxbOAwA8wKjCmxUIR2xONa9cFCjenVhQ/rwh3GNt2sDNKJDZCRkLkyq8CuAqqZPJrtJ52lKM7eni6VyvNFP2YQtofeqmrEgDWCSJa3GYGCT3WSaEdAtdV75zsjwMo3R5yNwBalHQJZOOc2nj5cqYaj97pJfF3EukL4yCjdoAkH7OSQB2eSk23o8kLXdbv8TgrYwuh9/b6DojdKhY6OlgoUWdAvrhe+/Wo3CJPFO2O3jtnD52RuUeZE/g9fd4prIdvN7lEQy5BkfDaFQUbSf5FTRlwGlGqFIlhj3AhHkZTuj2GP6tnFmDnAzQfdWrnaX1mnguVR1ui6ySEaTvA6zebHQhrMIvRgoqeL22FzCizHFH6ne80DYIMH/3awP1i1RMUCuF/0jJLPX1WnnsmVp7cVzwhpF+b+ySvLWRHCsDF6DsEJ7aAQ5B/T31OCD+G3I+ar7M0s2TtW8qXoOF6p0KHE2M96rL5NcuRD92cgBYRfDH+cyPsY1wSJXgD8gz3jjm44Itick9hYK9+g4XoP50=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
