travis:
  secure:
    BINSTAR_TOKEN: T/8QOGCdqPgghRmjCcpenYQBws6j5s9lETkxMjZamuwhboAZgpMPUF5PUQDoCHGNfPfiSwNU7OueSClsnWwFbcpEtMbKj+ZkYyUzN6SAT1Guv2b+vCtEFXzApc2qv0ypDuD2Z49E5E/NO71YkqWydkDTckimGoWJwsM069+T6leWhfgffIowu4YGsBbkbNLByO6ArjY2loXn2jnMUBZMTOfpK0ucZGB1IFnjBJxfQSlNig3nhwX80pE6Ahzse1HCa1M2SGQf5oGJJrSRNRP+6lEqH1lNQCbrYiWcpkRdpsQB/1eLcCHGh6Y1H6vW8jKryj2u5Q3gPIONkEJeuUEvP4xomYvoBTCjYoYN9jl3FArnxB3LAxG11gMJh62ISh6NavDPBILL3f5yV/AbmtyoyWruwFaru27MG0LoCgX1iQR9NpXRjBvUfKTreCbpicHIYZddzIWz+t9RffmncYSRCc1uB/mx05m0ARqE18YdUfTWdjmaAQbuWIYT/ctWW99OV/e51XN3JL1R4buaWVf9TR44WgatylgRO8a5pODYlvD33dxy1ZiAhI/R8WtERXnVzj2dqHycSX7GsmaRxrn4xGUNkp85bldR53CvU9JwQjdBSVrHU1jFFHvg6gSzqBL1ef6tLr9jObTab2egpCKx1BGQd9HDRXvfternwl8EFWg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
