travis:
  secure:
    BINSTAR_TOKEN: Y5n1Ntwe8y3mEPD6GIAlwo25Sb60Daz3zG4Uvd3K4ZpoUMsPnw2oRoH+CmzJQLJVcEatIdcAzXzUB+zxyHux51h+HLuTloYxkcGoohUwqRNhw72IWkBBeZgevaXz8QT5DQItSaKmwti7ewI1fdKwBtjqKu7nM7U9nDqGzQz1o7w0p2zkxa+Ilam3cEWwRPkvGDGnVfwM5yJwZXWx6SpzrAAzB/htIAe0xnZGx3YohOvz+XvCcimB0/7UbVfaUqb7Vx/W4eA9uGJp7JYMbWS2KNR911S43HIEpK0mWGNPqmDhALjB9GXXm4dFH+5a3dhOOqD6962iDZUVDb+mCsXpP4uXNR6Qzb93Fa1Lbw7KMW+6EqXr/m6Gft4I0GiXXITP29pwza8ocaIJUaFv5QacqjdmLrE73W3b9kTzFuJPXmDOb9G6ogcsv5hL8LpQGghtFfSudz+P9lvsqZGDkOkPEvTGXf51OASfzdzISE34/m71ck/JGLEKr/pHm/7PZ7BgKzXk9ZCQrVXPyrit5EuTsv3jatVkUW12hQK1l46D6HwYMzW5enh1TATl5eiYImctyriI1yNbymhmDX/HII6+p6NYcp9h3ZB6Wrv6QKQq+ll/b4IPgSQCfFDwXRg81GE2JIRNPlrmTd44AsoFDE/eJ3Q7pIfAf1LmpIfO0NlfNTM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
