{% set version="6.0" %}
{% set sha256="036d96991646d0449ed0aa952e4fbe21b476ce994abc276e49d30e686708bd37"  %}

package:
  name: unzip
  version: {{ version }}

source:
  url: ftp://ftp.info-zip.org/pub/infozip/src/unzip{{ version.replace(".", "") }}.tgz
  sha256: {{ sha256 }}
  patches:
    - 0001-use-CC-env-variable-for-build.patch

build:
  number: 0
  skip: True  # [win]
  script: mkdir -p $PREFIX/bin && make -f unix/Makefile generic && mv unzip $PREFIX/bin

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - unzip -h

about:
  home: http://www.info-zip.org/
  license: BSD-like
  license_file: LICENSE
  summary: simple program for unzipping files

extra:
  recipe-maintainers:
    - msarahan
    - jerowe
