travis:
  secure:
    BINSTAR_TOKEN: XSyGbcOsAzSmccQA1fryO4qVZKT3MRTabfBGLQdiANfOvDP47gOE+CyJW7S62OaHZHo4ds92qCPUUntCMn25QasYRpn8Nndn0J0Gprf8yGzwwdKCORTCHg3eIc/o3g01miRoHb/cYx/dj5PVTuz/8uhc0Tt6KIxtScViltGJMqsrvOkwda1MWbnB7ulKwaE73uqLg/9nMsRS46piYCFGayE5i3uX+SyCocLqe710Hv2g0CmNyKobAa3gKsWhE1OdA6Q0TAUgXNqeIvAzXRehQnK74Feq7rLDC2Mt5pQzoaYGjGbuG+JXt9jRx1I5wlg7S/SWum63uc/P61S2QdcMMNiWqDjCJfPf4qmb9xus6zg96qs24YDUUFpRZmVKKLrPegakBqW+M5w1oOQInocg+Hicb8f+FBrcZ6I0RCr7psC99oW2VVJOkXyM2q9WjC/1h5NwVBr3xH/vncClYGvgpth5n+QUv6b9iKVfL3WEHPP/4O2INLdbTZhISpjc8ovMea04KI/bCFQBd0dQWfEuhkXHx2nv3HSH+nyKP6KPs1HAmwkeiFa/b7UmVbXdQOEUGQIh4jDquEGssxOzCuZlyNxTp/d0VPdB+KGSIOYGIBcNURRH+wdq1OByswLT1We/32KvpuHTUJEBBdtbYIn8uAvvP3LElxQ7oa54MDizSXA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
