{% set name = "glob2" %}
{% set version = "0.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/miracle2k/python-glob2/archive/{{ version }}.tar.gz
  sha256: 4f554074f242f01b48a9537409cdbc5e31355a06b51950c95f93fc061c324149

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - glob2

about:
  home: https://github.com/miracle2k/python-glob2
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Version of the glob module that supports recursion via **, and can capture patterns.
  
  description: |
    The glob module finds all the pathnames matching a specified pattern according to the rules 
    used by the Unix shell, although results are returned in arbitrary order. No tilde expansion 
    is done, but *, ?, and character ranges expressed with [] will be correctly matched.
  doc_url: https://docs.python.org/3/library/glob.html
  dev_url: https://github.com/miracle2k/python-glob2
  doc_source_url: 

extra:
  recipe-maintainers:
    - dfroger
