travis:
  secure:
    BINSTAR_TOKEN: PBRMKpiHShzWWC/Ssfk8VXmjJZqZ78QpO73YSqqppmbU8uWYgbTRQljQbwlRLQJxpF3vLjuqw9r6uofrthkUUfRvKxu+qC1q2B+al86UemdBOiF8mLXyrqwaMNtZtfOkQhcFd5ITWJj7DJ3lydeAPfZd0evpy0j7nH/gv6RjscUItIT6+/H+n3HASrpcwtOO/Vo+e7GZgdA+ItlBJlG6XQ8RVofHjaRcS61WgHOQmmR0bg/DGlbaayhCZ5eVMpRNnq6Eifl2JPG2fItyynPwpl7/flDMkqXz6Ckw+DRDcMYMv49S3Z43QBaMbeggANgJ93kjqXZ+j0DEhEjo+KC/lTrMrFW1z+bPN+z5jLe2DKGz+pl7isy+YLC/CGNKb+GlqMMV6qbn2lOYbrXprIxgmxCDFU4c1Nc5Sm0UoM3S79+vXwVAPY9wAB/pXFR6UhD74Xfi/gtaXdJzv8+lqj0SNfcW7V5HmDNtwzqDNqXAcElsJ2MxctP4OyM4JXrxd+fQaNoZGYKKe1ibRQGCq7eI3DZO9lC6STA7TNrOaeJBjDu6F4yXIoWsmmtmvNRgt39uFCTEd8d0NVsTsOHLPxKwpt/I1ncys7ICnFW5laDwcHIcHUnUfoaWq+VQ9ko6rz1Ga/ClkPmc4eNWon2F/azkDSur3klwE4d0wy8WzPU9JOY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
