travis:
  secure:
    BINSTAR_TOKEN: jrSjoqvzYWXql7nJbieO15Wi0aS6cHTDni2cMaraWnOJShnHWG2RXGNPe0AASgtOpnLoJay784YhewbuHCONn6Y6KPdfWFV4YKD4+FbxT2yMGeW5S3f61Rdo8rVfXrVPfCw8Uw4+By7x6y87JpraDwaNXrl47jp/7za0lQ2nDleuEcYyv0H9t8JUTtZ8Fcf5LdH07WOuodt13sWS3JwD/dbrTcBd34xuqD94lNdSH1xkYgjzdpyP4tQaiE3CARfd47cS9PDkgG/jx12G1FkBjZbQITA/IKpvynVYO9+J8vmHnWLoPP0Rl/zewadSJRCWMzvPKg/tzjGNMG7xuFEuSXNs1hDtxEM1dZCfrsA9bus0Qijjaupq4gCqUC53GM2ahqlAAhVyj3LY055jnZvJLsfhqgFKUabdFRUtVov29kqBbKMBLyM6P6YvMtpTtAj6kUhkQKCk/b5NS/5NvC4rX7CYqv0p43/bQESwHtYOSHxY6/bUBgam0CKrASVUt4n0v7065GWwXETZifDk+piWpe0fGE1xW4wCoOhNeVDLhRUeHRrEgDNHG/cgw76zeNYHhKCfzUsCY5M8XGTSE3kKcTbG5Pbr/MdGlR3pLX121qz473c1L3s9KcdFh2Y7c2bub2eydHSSNPGUvdGwY5c9hSHG0L6Ya6QCedMEirDOOq4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
