travis:
  secure:
    BINSTAR_TOKEN: Um1AnDJJFYCfj/VumProlaqVr9BFDEia6q6Ts4QyA3mTIeNI0urByE/yzIbDxplUzO+YQYseLLIFRKAqL2lMVxIO3h9rQzlwBL5LgbENcVM3u01Ak8gsVOAIF6aNihlglJ9vWmnEfEPi4PPr3ud+eOm3WldoSjP1CicRzeNzWv11i+ikl5Ql8e5kQ+u9v4axyf4s0odooDkcqrO9R8pYlXyUbWNylOArTKVumFFnxsIUnP2VV2nPcaKKDsLS5L5U8qnaGz1mXlMtsG1G97wB+HU3/2FzOQaBNG0QiIR0J4VuYxrG9EZz8maa8frY2BA1Ckj1riHlCZxU9xic8m6JTZeVxF+4xdk0G4QXVqJn9HK1hiaPVDzvLJJ86K3GQB5E38x6044gNCzw3Le8qGd+j42emfaqHZgCwn1O2RrB3epcsJeHVB8wIgT6buwpxsZ9PTKsOWzqDPmqI21zNtbx0s6g/cU7VB8NE5qmMhVG0wLaRYPgDer7bQ6zpnEuHwh2r2gkPPwkuoOy8Gu+/oS1LWorb3JQDl9plSlLob3FrkDEdbYeLGNN2ya+r8Q8J683tlg1hKC+2lKco73kgO+9fMuOn5XHj4SmNeRNWdNIIcsKOYiB8H6xw0eweFDrJGf3/eakuc+linBksW9WH4+SSskKOuqtX1F0ecpDtP0/UC8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
