travis:
  secure:
    BINSTAR_TOKEN: KPlor6rNLEu648w7nUTdWvmJTwOhwqBBfmA4mDJkjI4u4yUbalcqNuVgBHze8Fy0y7O2SAKy4hQigw08O9Qwm7jCBwJB9sNGHfa+QfWSz9t5U+vsqe2y3dmtyOrQ9AyV/j7Goyg4F7DtBU0RuAEqZ4DVZJkTPZxoLWarZL4jHOBnqlme9RR9q7TQgSM2pFPGwArL9Tu8uRG6FK0xOoc3TmAOpZ/La6etH/2gO0cVmYDGtFYWZKW5noOwPIke0Xchcllhoffodj3Zk0LNaCNXmW9fdo9oxQeQxe4G108ETaYjnz4h0ScG7w0CPEPzrNA5UA7BlSvV8WtKG1q1n8Jp4G+ezLVn91oPuz1WYPULloMzMLlfGwW/uIe5N0PmnmB/fxkzmuzkLI7SESNiozEIvKJgm9Gb14afY/yi+1RZXLXKPEv1mPT0bMMAdiJcB/BlcrPbcxJPIGGiJKasaB1XUlpQUNu1xSCHMVBQ6xGhxsJ1RoiBM84BJ05LTu0+vmGK+Ec+Zwo5IHY6MTb9Xq8z+CZY8P/Sb/9wB5s8jEBZr5LBQtmuC3zYyZHUt5Gnwa69DKWzZ5d/yPqcg53B+r2RLm8vy8DrSZV9gU8VqEcWT4NpGUp4Pp92sYAvwMhxYfJWtw+dZZKR7WsaI0DYasP6SLwtbRGCmJWwZWofqo8qR9Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
